
project_id = "lstbjfcupoowfeunlcly"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true

[studio]
enabled = true
port = 54323

[functions.process-payment]
verify_jwt = true
